title: Nagarjun Chittyala
description: Machine Learning & Artificial Intelligence - Automation Portfolio
show_downloads: true
logo: /assets/img/nagarjun.jpg
google_analytics:
theme: jekyll-theme-cayman